# Number 1

In [6]:
import numpy as np
import matplotlib as plt

In [27]:
A = np.array ([[1,1,1,1],[2,-1,3,4],[-3,2,-2,5],[1,-1,4,-1]]) 

B = np.array([10,8,-3,5])


A1 = ((A[0]*2)-A[1])
sol = np.linalg.solve(A,B)

x , y , z , w = sol

print(mat)
print(x,y,z,w)
print(x+y+z+w)
print((2*x)-y+(3*z)+(4*w))
print((-3*x)+(2*y)-(2*z)+(5*w))
print(x-y+(4*z)-w)

[ 4 -2  6  8]
3.4433962264150946 4.698113207547171 1.6226415094339626 0.23584905660377356
10.000000000000004
8.0
-2.999999999999999
5.000000000000001


# Number 2

In [19]:
current = np.array([[1500,-600,0],[0,600,900],[1,1,-1]])
voltage = np.array([12,15,0])

cur = np.linalg.solve (current,voltage)

i1 , i2, i3 = cur

print (i1,i2,i3)
print ((i1*1500)-(i2*600))
print ((i2*600)+(i3*900))

0.00967741935483871 0.004193548387096773 0.013870967741935485
12.000000000000002
15.0


# Number 3

In [14]:
inverse = np.array([[2,1,3],[1,2,1],[3,1,2]])

answer = np.linalg.inv(inverse)

print (answer)

[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]
